### ISSUE TITLE
'model_management' is not defined

### ISSUE THREAD

**Issue by johnyboro** [Fannovel16/comfy_controlnet_preprocessors#60]
Broke when instaling

![image](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/63916529/ce7f6255-32b8-4db2-a486-2248afca3535)

**Comment by johnyboro** [comment]
Nodes seem to work fine so it might not be much of a problem

**Comment by KaruroChori** [comment]
https://github.com/Fannovel16/comfy_controlnet_preprocessors/pull/59 should fix that.

**Comment by MoonMoon82** [comment]
The installer still shows this error message..
![grafik](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/41437842/599e9851-f335-44cb-85db-384926d85d3c)
Any news on that?

Kind regards

**Comment by octoworld** [comment]
not a fix but i worked around this by commenting out line 27 of install.py
`#    midas.MidasDetector()`
It only seems to trigger for that model for some reason.

**Comment by jjangga0214** [comment]
@johnyboro Already fixed in [b0c04a2](https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/b0c04a2a48699e41fff2e6ceba6c61940ca68545), the latest version.
You should update and try.
 If working, please close this issue.

**Comment by jjangga0214** [comment]
Sorry for the confusion. It's not fixed in b0c04a2. 
#59 or #63 will fix it.

**Comment by jjangga0214** [comment]
The PR #63 is merged. You or @Fannovel16 can close this.

**Comment by Miru302** [comment]
Turns out this file has a bit of history :)
It was fixed twice which in the end rendered it broken again. I have a pr that removes the added 'comfy' prefix in the calls. Or alternatively it's possible revert the commit that adds it.
In any case I think it's better to import it as 'model_management', makes it a tiny bit less cluttered.

**Comment by jjangga0214** [comment]
> I have a pr that removes the added 'comfy' prefix in the calls.

Great to take an action.

> In any case I think it's better to import it as 'model_management', makes it a tiny bit less cluttered.

That's what maintainer should decide eventually.
In my case, I try to keep consistency when creating PR even though my preferred style is differ from it.
